version: 1.6.{build}
branches:
  only:
  - master
configuration: Release
platform: Any CPU
assembly_info:
  patch: true
  file: '**\AssemblyInfo.*'
  assembly_version: '{version}'
  assembly_file_version: '{version}'
  assembly_informational_version: '{version}'
before_build:
- cmd: nuget restore
build:
  publish_nuget: true
  verbosity: minimal
artifacts:
- path: /.*\.nupkg/
deploy:
- provider: NuGet
  api_key:
    secure: YCbMu8l9i4QgxqXQ6SfnRp0EGd6pJNVuqDhJ7eUCqtEV+oBnyRKfS6VajNwheZs6